version: '3.4'
services:
  rdp-vscode-dev-build:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ${IMAGE}:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspaces/rdp-vscode-devcontainer:cached
      - ${HOME}/.ssh:/root/.ssh:cached
    env_file:
      - ./.env
  rdp-vscode-dev-push:
    build: .
    image: ${REGISTRY_HOSTNAME}/${PROJECT_ID}/${IMAGE}:latest
