version: '3.8'
services:
  rdp-vscode-dev-build:
    build:
      context: ./
      args:
        BASE_IMAGE: ${BASE_IMAGE}
      dockerfile: ./Dockerfile
    image: ${DEV_IMAGE}:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    runtime: nvidia
    privileged: true
    ports:
      - "8787"
    volumes:
      - ${LOCALHOME}/rdp-vscode-devcontainer:/workspaces/rdp-vscode-devcontainer:cached
      - ${LOCALHOME}/.ssh:/root/.ssh:cached
    env_file:
      - ./.env
  rdp-vscode-dev-tag:
    extends: rdp-vscode-dev-build
    image: ${REGISTRY_HOSTNAME}/${PROJECT_ID}/${DEV_IMAGE}:latest
